### ISSUE TITLE
Ch07 문제 업로드

### ISSUE THREAD

**Issue by jae-hun-e** [Docker-K8s-study/docker-k8s#5]
### Q1. **도커 컴포즈의** up**,** down**,** stop **명령어 각각의 기능 설명ㄱㄱ**

- 새끼문제 볼륨도 없앨려면 쓰는 옵션은?

### Q2. 도커 컴포즈에서 depends_on의 역할은 무엇인가?

1. 컨테이너의 종료 순서를 지정한다.
2. 네트워크 연결을 설정한다.
3. 서비스 간 실행 순서를 지정한다.
4. 환경 변수를 설정한다.

### Q3. tmp/docker-compose.yml 안에서 demo라는 네트워크를 생성했다. 이때 도커 엔진이 읽게되는 네트워크의 이름은?

**Comment by Chaeyoung714** [comment]
1. Dockerfile과 docker-compose.yml 파일의 차이점은?
2. 도커 컴포즈에서는 컨테이너가 모인 것을 ____라고 부른다.
3. 다음 중 docker-compose.yml 작성 규칙이 아닌 것은? (2개)
    1. 첫줄에 도커 엔진 버전을 기재한다.
    2. 이름은 주항목 아래에 들여쓰기한 다음 기재한다.
    3. 콜론의 앞과 뒤에는 공백이 와야 한다.
    4. 들여쓰기는 같은 수의 배수만큼의 공백을 사용한다.
    5. 단독 항목을 기재할 땐 콜론 뒤에 바로 작성한다.
4. 도커컴포즈 파일의 설정 항목과 docker run 커맨드 상의 옵션 또는 인자가 올바르게 매핑되지 않은 것은?
    1. networks : —net
    2. volumes : -v
    3. ports : -p
    4. container_name : —name
    5. depends_on : -d
5. 현재 디렉토리에 있는 docker-compose.yml 파일을 실행하려고 한다. 실행 시 컨테이너는 백그라운드로 실행할 것이다. 명령어를 최대한 간단히 써보자

**Comment by Jin409** [comment]
다음 중 **도커 컴포즈(Docker Compose)와 Dockerfile의 차이점**에 대한 설명으로 **옳지 않은 것**은?

1. 도커 컴포즈는 여러 개의 `docker run` 명령어를 대신 실행하는 것과 같은 역할을 한다.
2. 도커 컴포즈는 컨테이너뿐만 아니라 네트워크와 볼륨도 함께 생성할 수 있다.
3. Dockerfile은 컨테이너를 생성하는 과정에서 네트워크는 자동으로 생성할 수 없지만, 볼륨은 생성할 수 있다.
4. Dockerfile은 새로운 이미지를 만들기 위한 설정 파일이다.
5. 도커 컴포즈를 사용하면 여러 개의 컨테이너를 쉽게 관리할 수 있다.

아래와 같은 도커 컴포즈 설정 파일에서 version 이 의미하는 바로 **옳지 않은** 것은?

```yaml
version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - my_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
```

1. `version`은 도커 이미지의 버전을 의미하며, 여기서는 `3.8` 버전의 nginx와 redis 이미지를 사용한다.
2. `version`은 도커 컴포즈 파일의 구문과 기능을 정의하는 버전을 의미한다.
3. `version`은 도커 컴포즈가 해당 파일을 해석할 때 따르는 문법 및 기능의 기준을 결정하는 역할을 한다.


다음 중 **`docker-compose` 명령어의 옵션 설명으로 옳지 않은 것**은?

1. `-no-deps` 옵션을 사용하면, 특정 서비스만 단독으로 실행되고 의존하는 다른 서비스는 실행되지 않는다.
2. `-force-recreate` 옵션을 사용하면 `docker-compose.yml`이 변경되지 않았어도 컨테이너가 강제로 재생성된다.
3. `-no-build` 옵션을 사용하면 필요한 이미지가 없어도 자동으로 빌드하여 실행된다.
4. `-abort-on-container-exit` 옵션을 사용하면 여러 개의 컨테이너 중 하나라도 종료되면 나머지도 함께 종료된다.
5. `-remove-orphans` 옵션을 사용하면 `docker-compose.yml`에 정의되지 않은 컨테이너가 자동으로 삭제된다.
